### ISSUE TITLE
Get Global reporters for single manager.

### ISSUE THREAD

**Issue by artgitex** [rod4n4m1/ibm-bluepages-js#11]
Hello,
I should say that this app is very useful! Thank you.
However, it is nice to have a possibility to get the list of Global reporters for the specific manager.
There is getDirectReportsByW3ID(id) function and this function works fine, but only gets In Country reporters.
Could you please check if it is possible to extend this app with the new function for Global reporters.
![image](https://user-images.githubusercontent.com/45820574/89617702-608f0800-d893-11ea-8502-c0d0af588943.png)

Thank you in advance.

**Comment by rod4n4m1** [comment]
Thanks Artsiom, we will investigate this story and check if we can build a new function.

**Comment by rod4n4m1** [comment]
I just implemented `getDirectGlobalReportsByW3ID` function that returns global reportees.
